export const cashCut = [
  {
    comments: "Faltante de 60",
    user: "rodrigo",
    Ayer: 3084,
    Inicio: 3084,
    Final: 3084,
    Kyte: 0,
    credit: 0,
    cash: 0,
    diffCashCredit: 0,

    shipments: [
      { Melch: 0 },
      { Victor: 0 },
      { Tepa: 0 },
      { Pops: 0 },
      { Total: 0 },
    ],
    incomes: [
      { description: "Rappi", amount: 0 },
      { description: "Didi", amount: 0 },
      { description: "Tarjeta crédito", amount: 0 },
      { description: "Depositos y/o tranferencia", amount: 0 },
      { Total: 0 },
    ],
    expenses: [
      { Descripción: "", amount: 0 },
      { Descripción: "", amount: 0 },
      { Descripción: "", amount: 0 },
      { Descripción: "", amount: 0 },
      { Descripción: "", amount: 0 },
      { Descripción: "", amount: 0 },
      { Total: 0 },
    ],
    bills: [
      { Valor: 1000, Cantidad: 0 },
      { Valor: 500, Cantidad: 0 },
      { Valor: 200, Cantidad: 0 },
      { Valor: 100, Cantidad: 0 },
      { Valor: 50, Cantidad: 0 },
      { Valor: 20, Cantidad: 0 },
      { Total: 0 },
    ],
    coins: [
      { Valor: 20, Cantidad: 0 },
      { Valor: 10, Cantidad: 0 },
      { Valor: 5, Cantidad: 0 },
      { Valor: 2, Cantidad: 0 },
      { Valor: 1, Cantidad: 0 },
      { Valor: 0.5, Cantidad: 0 },
      { Total: 0 },
    ],
  },
];
